import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const epilogue = Epilogue({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={epilogue.className}>
        {children}
        <Toaster position="bottom-center" closeButton richColors />
      </body>
    </html>
  );
}
